
---
title: "Comparing SAS and R - Linear Models"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: lumen
    highlight: default
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
  #  code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(broom)
library(tidyverse)
library(kableExtra)
library(DT)

datapath <- "C:/Users/User/OneDrive - ManpowerGroup/_ExperisStuff/PHUSE/CSRMLW/CSRMLW/linear_models/Example  50.2 Regression with Mileage Data/"

mileage <- 
  read_sas(paste0(datapath,"mileage.sas7bdat")) %>% 
  mutate(mph_sq = mph^2)

sas_fitstatistics <- read_sas(paste0(datapath, "fitstatistics.sas7bdat"))
sas_oaanova <- read_sas(paste0(datapath, "overallanova.sas7bdat"))
sas_parameterestimates <- read_sas(paste0(datapath, "parameterestimates.sas7bdat"))
sas_predictedvalues <- read_sas(paste0(datapath, "predictedvalues.sas7bdat"))


# changed block to be a character variable so the aov()
# function treated it as a class variable.
# mileage <- tribble(
#   ~mph, ~mpg,  
#   20, 
#   15.4,
#   30, 
#   20.2,
#   40 ,
#   25.7,
#   50 ,
#   26.2,  
#   50 ,
#   26.6,  
#   50 ,
#   27.4,
#   55   ,
#   NA,
#   60 ,
#   24.8
#   ) %>% 
#   mutate(mph_sq = mph^2)

```

#### glm()

## Example 50.2 - Regression with Mileage Data

### The Data
#### HTML Table - Using DT
```{r DT-output, echo = TRUE}
mileage %>% DT::datatable()
```

### Model call
#### From R
```{r  R Model, echo = TRUE}
lm1 <- lm(mpg ~ mph + mph_sq, data = mileage) 
```

#### From SAS
```{r  SAS Model, echo = TRUE}
# ods output overallanova=ex50_2.overallanova;
# ods output parameterestimates=ex50_2.parameterestimates;
# ods output predictedvalues=ex50_2.predictedvalues;
# ods output fitstatistics=ex50_2.fitstatistics;
# proc glm data=ex50_2.mileage;
#    model mpg=mph mph*mph / p clm;
# run;
# quit;
```
### Fit Statistics
#### From R
```{r  R Fit Statistics, echo = TRUE}
glance(lm1) %>% DT::datatable()
```
#### From SAS
```{r lm -SAS Fit Statistics, echo = TRUE}
sas_fitstatistics %>% DT::datatable()
```

### ANOVA Summary
#### From R
```{r  R ANOVA Summary, echo = TRUE}
glance(lm1) %>% 
  DT::datatable()
```

#### From SAS
```{r  SAS ANOVA Summary, echo = TRUE}
sas_oaanova %>% DT::datatable()
```

### Parameter Estimates
#### From R
```{r  R Parameter Estimates, echo = TRUE}
lm1 <- lm(mpg ~ mph + mph_sq, data = mileage) 

tidy(lm1) %>% DT::datatable()
```
#### From SAS
```{r lm -SAS Parameter Estimates, echo = TRUE}
sas_parameterestimates %>% DT::datatable()
```

#### Parameter Estimate Differences |R - SAS|
```{r lm -SAS Parameter Estimates Diff, echo = FALSE}
r_parameterestimates <-
  tidy(lm1)  %>% 
  mutate(Parameter = case_when(term == "(Intercept)" ~ "Intercept",
                               term == "mph_sq" ~ "mph*mph",
                               TRUE ~ term)) %>% 
  select(-term)
  

sas_parameterestimates %>% 
  inner_join(r_parameterestimates, by = c("Parameter"="Parameter")) %>%
  mutate(diff_estimate = abs(estimate - Estimate),
         diff_stderr = abs(std.error - StdErr),
         diff_tvalue = abs(statistic - tValue),
         diff_probt  = abs(p.value - Probt)) %>% 
  select(diff_estimate, diff_stderr, diff_tvalue, diff_probt) %>% 
  DT::datatable()
```

### Predicted Values
#### From R
```{r lm - R Predictions, echo = TRUE}

augment_lm1 <- augment(lm1)


r_fitcl <- as.data.frame(predict(lm1, interval="confidence"))  %>% 
  rownames_to_column(var="Observationc") %>%
  mutate(Observation = as.numeric(Observationc)) %>% 
  select(-fit, -Observationc) 

r_predictedvalues <-
  augment_lm1 %>% 
  mutate(Observation = as.numeric(.rownames)) %>% 
  full_join(r_fitcl, by = c("Observation"="Observation")) %>%  
  select(Observation, mpg, mph, .fitted, .resid, lwr, upr) 

r_predictedvalues %>% 
  DT::datatable()


```

#### From SAS
```{r lm - SAS Predictions, echo = TRUE}

sas_predictedvalues %>% DT::datatable()

```

#### Predition Differences |R - SAS|
```{r lm - Prediction Differences, echo = FALSE}


sas_predictedvalues %>% 
  full_join(r_predictedvalues, by = c("Observation"="Observation")) %>%
  mutate(diff_fitted = abs(.fitted - Predicted),
         diff_resid = abs(.resid - Residual),
         diff_lowercl = abs(lwr - LowerCL),
         diff_uppercl = abs(upr - UpperCL)) %>% 
  select(Observation, mpg, mph, diff_fitted, diff_resid, 
         diff_lowercl, diff_uppercl) %>% 
  DT::datatable()

```




