---
title: "Takeaways"
author: "CMH Subgroup"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc : true
    toc_float: true
    number_sections: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. To get the same output (incl. Chi-sqaure statistics, odds ratio and homogeneity test) more than one package is needed in R.

2. The most methodologically mature package is the VCD extra package, however it comes with some bugs and has its problems with sparse data. For a simple 2x2xk design multiple other packages can be used and provide reliable results. 

3. The r-packages are way more sensitive towards methodologically questionable designs and data proportions. They throw warnings or errors to give the user feedback whereas SAS just prints the resulting output no matter how the underlying data look like. 

4. Consult the documentation for each R function to be used to understand any defaults that are applied (e.g. continuity correction).



